config/routes.rb
Rails.application.routes.draw do

  resources :products, :categories
  
  get 'letters/:id' => 'letters#show', as: :letters
  get 'alphabets'     => 'letters#index'
  
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/letter.rb
class Letter
  extend ActiveModel::Naming
  attr_reader :char
  
  def initialize(char)
    @char = char
  end
  
  def self.all
    ('A'..'Z').map { |c| new(c) }
  end
  
  def self.find(param)
    all.detect { |l| l.char == param } 
  end
    
  # This method is no longer required because we are not using letter resource
  # def to_param
  #   @char.downcase
  # end
  
  def products
    Product.where("name LIKE ?", @char + '%').order("name")
  end
  
  def to_model
    # You will get to_model error, if you don't have this dummy method
  end
  # You need this otherwise you get an error
  def persisted?
    false
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(allowed_params)
    if @category.save
      flash[:notice] = "Successfully created category."
      redirect_to @category
    else
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated category."
      redirect_to @category
    else
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Successfully destroyed category."
    redirect_to categories_url
  end
  
  private
  
  def allowed_params
    params.require(:category).permit!
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  def index
    @letters = Letter.all
  end

  def show
    @letter = Letter.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.limit(10)
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(allowed_params)
    if @product.save
      flash[:notice] = "Successfully created product."
      redirect_to @product
    else
      render :new
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated product."
      redirect_to @product
    else
      render :edit
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Successfully destroyed product."
    redirect_to products_url
  end
  
  private
  
  def allowed_params
    params.require(:product).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tles</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
            
      <%= yield %>
    </div>
  </body>
</html>

app/views/letters/index.html.erb
<% for letter in @letters %>
  <%= link_to letter.char, letters_path(id: letter.char) %>
<% end %>

app/views/letters/show.html.erb
<h1> Products for Letter <%= @letter.char %> </h1>

<p><%= link_to "Select a Letter", alphabets_path %></p>

<%= render :partial => @letter.products %>

app/views/products/_form.html.erb
<% form_for @product do |f| %>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/products/_product.html.erb
<div class="product">
  <h3>
    <%= link_to h(product.name), product %>
    <%= number_to_currency(product.price) %>
  </h3>
  <div class="actions">
    <%= link_to "Edit", edit_product_path(product) %> |
    <%= link_to "Destroy", product, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<%= render :partial => @products %>

<p><%= link_to "New Product", new_product_path %></p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>